//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioForeignKit.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Patients
    {
        public string UserId { get; set; }
        public string RoleId { get; set; }
        public int DiagnosticId { get; set; }
        public int NationalityId { get; set; }
        public int GenderId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string ClinicComment { get; set; }
        public string DoctorComment { get; set; }
        public Nullable<System.DateTime> DoctorCommentDate { get; set; }

        public Nullable<System.DateTime> DiagnosticDate { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<System.DateTime> IncomingPatientDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Diagnostics Diagnostics { get; set; }
        public virtual Genders Genders { get; set; }
        public virtual Nationalities Nationalities { get; set; }
    }
}
